adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.google.android.apps.messaging
adb shell pm uninstall --user 0 com.google.android.music
adb shell pm uninstall --user 0 com.google.android.apps.docs
adb shell pm uninstall --user 0 com.google.android.apps.photos
adb shell pm uninstall --user 0 com.google.android.apps.maps
adb shell pm uninstall --user 0 com.google.android.apps.docs.oem
adb shell pm uninstall --user 0 com.asus.calculator
adb shell pm uninstall --user 0 com.facebook.katana
adb shell pm uninstall --user 0 com.facebook.orca
adb shell pm uninstall --user 0 com.facebook.system
adb shell pm uninstall --user 0 com.facebook.appmanager
adb shell pm uninstall --user 0 com.instagram.android
adb shell pm uninstall --user 0 com.google.android.calendar
adb shell pm uninstall --user 0 com.cleanmaster.security
adb shell pm uninstall --user 0 com.asus.laserruler
adb shell pm uninstall --user 0 com.asus.quickmemo
adb shell pm uninstall --user 0 com.asus.quickmemoservice
adb shell pm uninstall --user 0 com.asus.supernote
adb shell pm uninstall --user 0 com.asus.weathertime
adb shell pm uninstall --user 0 com.google.android.videos
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.talk
adb shell pm uninstall --user 0 com.amazon.kindle
adb shell pm uninstall --user 0 com.asus.fmradio
adb shell pm uninstall --user 0 com.asus.contacts
adb shell pm uninstall --user 0 com.asus.microfilm
adb shell pm uninstall --user 0 com.asus.collage
adb shell pm uninstall --user 0 com.asus.ephotoburst
adb shell pm uninstall --user 0 com.asus.userfeedback
adb shell pm uninstall --user 0 com.asus.contacts.theme.dark
adb shell pm uninstall --user 0 com.asus.zencircle
adb shell pm uninstall --user 0 com.asus.task
adb shell pm uninstall --user 0 com.asus.taskwidget
adb shell pm uninstall --user 0 com.ecareme.asuswebstorage
adb shell pm uninstall --user 0 com.android.sharedstoragebackup
adb shell pm uninstall --user 0 com.eostek.asuszenflash
adb shell pm uninstall --user 0 com.asus.sharerim
adb shell pm uninstall --user 0 com.asus.splendid
adb shell pm uninstall --user 0 com.asus.splendidcommandagent
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0 
# adb shell pm uninstall --user 0
#installation section
